import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import styles from "./layout.module.scss";
import Providers from "./provider/Providers";

// I defined my fonts here. Fonts that don't with .woff2 were pushed to global.css folder
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const avenirNext = localFont({
  src: [
    {
      path: "../public/fonts/AvenirNext-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/AvenirNext-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/AvenirNext-DemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    // {
    //   path: "../public/fonts/AvenirNextLTPro-Bold.woff",
    //   weight: "700",
    //   style: "normal",
    // },
  ],
  variable: "--font-avenir-next",
});
const workSans = localFont({
  src: [
    {
      path: "../public/fonts/WorkSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/WorkSans-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/WorkSans-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/WorkSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-work-sans",
});
const roboto = localFont({
  src: [
    {
      path: "../public/fonts/Roboto-Regular.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${avenirNext.variable} ${workSans.variable} ${roboto.variable} ${styles.html}`}
    >
      <body className={styles.body}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
